//import logo from './logo.svg';
import './App.css';

function App() {
  console.log("we here")
  return (
    <div className="App">
      
      <header className="App-header">
        <div>
          Gymstagram
        </div>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        <PostComponent/>
        
      </header>

      

    </div>
  );
}

function PostComponent(){
  console.log("hi")
  return(
        <div className= 'container'> 
          <div id = "square">
            this is a post
          </div>
        </div>
  )

}
//hi
export default App;
